name: github pages

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - run: git config --global user.email "maximiseuk@gmail.com"
    - run: git config --global user.name "Maximise Team"
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci

    - run: npm run build
    - run: npm install --save gh-pages
    - run: npm run deploy
